site_name: Meta Docs
site_url: http://MetaBake.org
repo_url: http://MetaBake.org
copyright: (copyright MetaBake | cekvenich)
pages:
   - Home: index.md
   - Cloud Mount: cloud_mount.md
   - Reference: ref.md
   - Resources: res.md
   - About: about.md

theme: readthedocs
