
# editors app
thisPort: 9080
# app port - the one you are maintaining
appPort: 9082
appMount: /home/admin/prod

#
firebase_auth_json: auth-f959b-96034aadd9c1.json

# uses firebase auth
editorAPIport: 9081


