
# editors www app
editorsWwwPort: 9080

# admin users www app
adminWwwPort: 8080

# app port (blog www)- the one you are maintaining
appPort: 9082
# app url (blog www)- the one you are maintaining
appMount: /Users/liza/work/mbakeCLI/CMS

# uses firebase auth
editorAPIport: 9081

# uses basic auth
secret: '123456'
adminAPIport: 3030

corsUrlProd: ['http://localhost:9080']
corsUrlAdmin: ['http://localhost:8080']