"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Serv_1 = require("mbake/lib/Serv");
const editor_1 = require("./lib/editor");
const admin_1 = require("./lib/admin");
const mainAppG = Serv_1.ExpressRPC.makeInstance(['http://localhost:9080']);
const appGPORT = '9081';
const editorRoutes = new editor_1.EditorRoutes();
mainAppG.use('/api/editors', editorRoutes.routes());
mainAppG.use('/editors', Serv_1.ExpressRPC.serveStatic('www'));
const adminRoutes = new admin_1.AdminRoutes();
mainAppG.use('/api/admin', adminRoutes.routes());
mainAppG.use('/admin', Serv_1.ExpressRPC.serveStatic('wwwAdmin'));
mainAppG.listen(appGPORT, () => {
    console.log(`mainAppG listening on port ${appGPORT}!`);
    console.log(`======================================================`);
    console.log(`App is running at http://localhost:${appGPORT}/editors/`);
    console.log(`Admin is running at http://localhost:${appGPORT}/admin/`);
    console.log(`======================================================`);
});
